---
title: "Fall 2021 SimOps Final"
author: "Michael, Zach, Katie, Ellie "
date: ""
output: 
  revealjs::revealjs_presentation:
    theme: black
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE, message = FALSE, warning = FALSE)
```

## Stocking Shelves

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>

```{r ShelvesCode}
library(scales)

library(ROI)
library(ROI.plugin.lpsolve)
library(ROI.plugin.glpk)


products <- c("flower (3.5 grams)", "pre-rolls (1 gram)", 
                       "concentrates (1 gram)", "edibles (100 mg)")

costs <- c(25, 5, 50, 10)

demandProportions <- c(0.37, 0.15, 0.20, 0.28)

objectiveValues <- c(45, 12, 60, 15)

constraintValues <- c(850000, rep(0, 4))

zero_diag_matrix <- matrix(1,nrow=4,ncol=4) - diag(4)

demand_constraint_matrix <- (zero_diag_matrix * demandProportions * -1) + diag(4) * (1 - demandProportions)

constraintMatrix <- rbind(unlist(costs),
                         demand_constraint_matrix)

stockingShelvesOP <- OP(objective = objectiveValues, 
               constraints = L_constraint(L = constraintMatrix, 
                                          dir = c('<=', rep('==', 4)),
                                          rhs = constraintValues), 
                                          types = rep("I", 4),
                                          maximum = TRUE)

stockingShelvesOP_Result <- ROI_solve(stockingShelvesOP, solver = "lpsolve")

shelvingSolutionProduction <- data.frame(lapply(setNames(comma(stockingShelvesOP_Result$solution, accuracy = 1), products), type.convert),  
                                         stringsAsFactors=FALSE, check.names=FALSE)
shelvingSolutionRevenue <- data.frame(Revenue = dollar_format()(stockingShelvesOP_Result$objval))

shelvingSolutionExpenditures <- data.frame(lapply(setNames(dollar_format()(stockingShelvesOP_Result$solution * costs), products), type.convert),  
                                         stringsAsFactors=FALSE, check.names=FALSE)

shelvingSolutionPercentBudget <- data.frame(lapply(setNames(percent(sapply(stockingShelvesOP_Result$solution * costs, function(x){x/850000})), 
                                                            products), type.convert), 
                                            stringsAsFactors=FALSE, check.names=FALSE)

```

```{r ShelvesOutput, include=TRUE, echo=FALSE}
knitr::kable(shelvingSolutionProduction, caption = "Optimal Units by Product")
knitr::kable(shelvingSolutionExpenditures, caption = "Expentitures by Product")
knitr::kable(shelvingSolutionRevenue)
```

## Employees

```{r Employees}
library(tidyr)
library(ompr)
library(ompr.roi)
library(ROI.plugin.glpk)

job_preferences <- load("./data/job_preference_list.RData")

spread_data <- spread(job_preference, jobType, preference)

preference_data <- rownames(spread_data) <- spread_data$personName

preference_data <- spread_data[c("bud tending", "customer service", "marketing", "security")]

employees <- as.integer(nrow(spread_data))
departments <- 4
capacity <- rep.int(5, departments)

# Function to Pull Preferences of Each Employee/Row
weight <- function(employee, department) preference_data[employee, department]

model <- MIPModel() %>%
  # 1 if employee i is assigned to department j
  add_variable(x[i, j], i = 1:employees, j = 1:departments, type = "binary") %>%
  
  # maximize the preferences
  set_objective(sum_expr(weight(i, j) * x[i, j], i = 1:employees, j = 1:departments)) %>%
  
  # we cannot exceed the capacity of a department (5)
  add_constraint(sum_expr(x[i, j], i = 1:employees) <= capacity[j], j = 1:departments) %>% 
  
  # each employee needs to be assigned to one department
  add_constraint(sum_expr(x[i, j], j = 1:departments) == 1, i = 1:employees)

model

result <- solve_model(model, with_ROI(solver = "glpk"))

result <- get_solution(result, x[i, j])

result <- result[result$value == 1, c("i", "j")]

team_results <- dplyr::left_join(spread_data, result, by=c("personID"="i"))

team_results$department <- ifelse(team_results$j==1, "bud tending",
                       ifelse(team_results$j==2, "customer service",
                              ifelse(team_results$j==3, "marketing",
                                     "security")))

team_results <- team_results[,c("personName", "department")]
```

<div class="col2">
```{r EmployeeOutput, include=TRUE, echo=FALSE}
knitr::kable(team_results)
```
</div>


## Shipping

```{r Shipping lpSolve}
library(linprog)

objective_values2 <- c(10, 8, 12, 20, 
                    10, 8, 12, 20, 
                    5, 10, 5, 25,
                    10, 8, 12, 20)
 
names(objective_values2) <- c("Better Provisioning, Ann Arbor", "Better Provisioning, Muskegon", 
                       "Better Provisioning, Utica", "Better Provisioning, Traverse City",
                       "Harbor Farmz, Ann Arbor", "Harbor Farmz, Muskegon", 
                       "Harbor Farmz, Utica", "Harbor Farmz, Traverse City",
                       "Hazy Farms, Ann Arbor", "Hazy Farms, Muskegon", 
                       "Hazy Farms, Utica", "Hazy Farms, Traverse City",
                       "Rare Michigan Genetics, Ann Arbor", "Rare Michigan Genetics, Muskegon", 
                       "Rare Michigan Genetics, Utica", "Rare Michigan Genetics, Traverse City")

constraint_values2 <- c(700, 300, 550, 420, 650, 200, 450, 250)

constraint_matrix2 <- rbind(c(1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 
                            c(0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0),
                            c(0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0),
                            c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1),
                            c(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0),
                            c(0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0),
                            c(0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0),
                            c(0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1))

constraint_directions2 <- c(rep("<=",4), rep(">=",4))

solved_model2 <- solveLP(cvec = objective_values2, 
                        bvec = constraint_values2, 
                        Amat = constraint_matrix2, 
                        maximum = FALSE, 
                        const.dir = constraint_directions2, lpSolve = TRUE)

solved_model2$opt

lpSolveDF <- data.frame(solved_model2$solution)
lpSolveDF <- setNames(lpSolveDF, 'Flower')
```

```{r Shipping glpk}
objectiveFunction <- c(10, 8, 12, 20, 
                    10, 8, 12, 20, 
                    5, 10, 5, 25,
                    10, 8, 12, 20)

names(objectiveFunction) <- c("Better Provisioning, Ann Arbor", "Better Provisioning, Muskegon", 
                       "Better Provisioning, Utica", "Better Provisioning, Traverse City",
                       "Harbor Farmz, Ann Arbor", "Harbor Farmz, Muskegon", 
                       "Harbor Farmz, Utica", "Harbor Farmz, Traverse City",
                       "Hazy Farms, Ann Arbor", "Hazy Farms, Muskegon", 
                       "Hazy Farms, Utica", "Hazy Farms, Traverse City",
                       "Rare Michigan Genetics, Ann Arbor", "Rare Michigan Genetics, Muskegon", 
                       "Rare Michigan Genetics, Utica", "Rare Michigan Genetics, Traverse City")

constraintValues <- c(700, 300, 550, 420, 650, 200, 450, 250)

constraintMatrix <- rbind(c(1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 
                            c(0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0),
                            c(0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0),
                            c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1),
                            c(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0),
                            c(0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0),
                            c(0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0),
                            c(0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1))

constraintDirections <- c(rep("<=",4), rep(">=",4))

library(ROI)

library(ROI.plugin.glpk)

solved <- OP(objective = objectiveFunction, 
           constraints = L_constraint(L = constraintMatrix, 
                                      dir = constraintDirections, 
                                      rhs = constraintValues), 
           maximum = FALSE, types = (rep("I",length(objectiveFunction))))

result <- ROI_solve(solved)

glpkDF <- data.frame(solution(result))
glpkDF <- setNames(glpkDF, 'Flower')
```

<div class = "col2">
```{r ShippingOutput, include=TRUE, echo=FALSE}
knitr::kable(lpSolveDF, caption = paste("Shipping Flower- lpSolve Cost: ", solved_model2$opt))
```
</div>

## Shipping Continued
<div class = "col2">
```{r ShippingOutput2, include=TRUE, echo=FALSE}
knitr::kable(glpkDF, caption = paste("Shipping Flower- glpk Cost: ", result$objval))
```
</div>


